  steps:
- id: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-app', '-f', 'Dockerfile.react', '.']
  dir: '.'

- id: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gradio-app', '-f', 'Dockerfile.gradio', '.']
  dir: '.'

- id: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/react-app']

- id: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gradio-app']

images:
- 'gcr.io/$PROJECT_ID/react-app'
- 'gcr.io/$PROJECT_ID/gradio-app'

substitutions:
  _REGION: 'us-central1'

timeout: '900s'

options:
logging: 'CLOUD_LOGGING_ONLY'

- id: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy react-app --image gcr.io/$PROJECT_ID/react-app --platform managed --region $_REGION --allow-unauthenticated
      gcloud run deploy gradio-app --image gcr.io/$PROJECT_ID/gradio-app --platform managed --region $_REGION --allow-unauthenticated
