options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'us-central1'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app', '.']
  dir: '.'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-app']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy my-app --image gcr.io/$PROJECT_ID/my-app --platform managed --region $_REGION --allow-unauthenticated

images:
- 'gcr.io/$PROJECT_ID/my-app'

timeout: '900s'
